name: Upload Website

on:
  push:
    branches:
    - main  # Trigger workflow only on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner
    steps:
    - name: Checkout
      uses: actions/checkout@v2  # Step 1: Checkout your repository code

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2  # Step 2: Set up AWS credentials for CLI access
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  # AWS access key from GitHub secrets
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # AWS secret key from GitHub secrets
        aws-region: us-east-1  # AWS region

    - name: Deploy static site to S3 bucket
      run: aws s3 sync ./public/ s3://july16sushantpaudelbucket --delete  # Step 3: Sync local 'public' folder to S3 bucket, deleting